### ISSUE TITLE
Making the plugin compliant with latest version of psi4

### ISSUE THREAD

**Issue by ashutoshvt** [CrawfordGroup/CCReorganization#1]
Due to recent changes in the psi4's source code, this plugin fails to build with psi4's latest version.
The problem appears due to removal of  libparallel from psi4. Also, I get a weird error in reorder_qt functions used in hamiltonian.cc and perturbation.cc.
```
/home/akumar1/newriver/ugacc/ugacc/hamiltonian.cc:36:34: error: invalid cast from type ‘const psi::Dimension’ to type ‘int*’ 
 reorder_qt((int *) ref->doccpi(), (int *) ref->soccpi(), (int *) ref->frzcpi(), (int *) ref->frzvpi(),..)

```
If I do something like: 
``` 
Dimension Doccpi = ref->doccpi() ;
int * p_doccpi = (int *) Doccpi;
reorder_qt( p_doccpi, .....)
```
the error is fixed but I don't know why the previous case gives errors. After we resolve this, I am going to create a pull request.

**Comment by amjames** [comment]
This works  because the cast from `psi::Dimension` -- > `(int *)` works fine. But the cast from `const psi::Dimension` --> `(int *)`  Doesn't.  However creating a `psi::Dimension` object from a `const psi::Dimension` object is fine.

I simplified the above lines to 

```c++
Dimension doccpi = ref->doccpi();
reorder_qt((int*) doccpi, ...);
```

And everything works fine. PR incoming with this and a few other updates related to changes in psi4.
